---
# Copyright 2015, Rackspace US, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: Copy in sample dhcpd.conf file
  copy:
    src: dhcpd.conf
    dest: /etc/dhcp/
  when: ironic_standalone
  notify:
    - Restart isc-dhcp-server
  tags:
    - tftpd-hpa

- name: Create /tftpboot
  file:
    path: "/tftpboot"
    state: directory
    owner: "{{ ironic_system_user_name }}"
    group: "{{ ironic_system_group_name }}"
    mode: "0755"
  when: ironic_standalone
  tags:
    - tftpd-hpa

- name: Copy in tftpd-hpa config file
  copy:
    src: tftpd-hpa
    dest: /etc/default/tftpd-hpa
  when: ironic_standalone
  notify:
    - Restart tftpd-hpa
  tags:
    - tftpd-hpa

- name: Copy in tftpd-hpa map file
  copy:
    src: map-file
    dest: /tftpboot/map-file
  when: ironic_standalone
  notify:
    - Restart tftpd-hpa
  tags:
    - tftpd-hpa

- name: Check to see if pxlinux.0 is required
  stat: path=/tftpboot/pxelinux.0
  register: pxelinux_exists
  when: ironic_standalone
  tags:
    - tftpd-hpa

- name: Check to see if chain.c32 is required
  stat: path=/tftpboot/chain.c32
  register: chain32_exists
  when: ironic_standalone
  tags:
    - tftpd-hpa

- name: Check pxlinux.0 exists
  stat: path=/usr/lib/syslinux/pxelinux.0
  register: pxelinux_stat
  when: not pxelinux_exists and ironic_standalone
  tags:
    - tftpd-hpa

- name: Copy syslinux pxlinux.0
  command: cp /usr/lib/syslinux/pxelinux.0 /tftpboot/pxelinux.0
  when: not pxelinux_exists and pxelinux_stat.stat.exists and ironic_standalone
  tags:
    - tftpd-hpa

- name: Copy syslinux chain.c32
  command: cp /usr/lib/syslinux/chain.c32 /tftpboot/chain.c32
  when: not chain32_exists and chain32_stat.stat.exists and ironic_standalone
  tags:
    - tftpd-hpa
